<?php

/**
 * @file
 * Contains cadetsviews.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cadetsviews_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cadetsviews module.
    case 'help.page.cadetsviews':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>Please see <a href="https://github.com/JoineryHQ/cadetsviews#readme">README.md</a>.</p>';
      return $output;

    default:
  }
}
